name: CI Build
on:
  pull_request:
  # By default, the pull_request event type is not triggered when a PR is merged into main
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies
        # Ubuntu 16+ does not install libgconf-2-4 by default, so we need to install it ourselves (for Cypress)
        run: |
          sudo apt-get install libgconf-2-4
          yarn --immutable
      - name: Run linting
        run: yarn lint:js
      - name: Run unit tests
        run: yarn test
      - name: Upload unit test coverage
        if: success()
        uses: codecov/codecov-action@e0b68c6749509c5f83f984dd99a76a1c1a231044 # v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
      - name: Run e2e tests
        run: yarn e2e
      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        with:
          name: OperationsGateway Screenshots
          path: cypress/screenshots
