name: Playwright Tests
on:
  pull_request:
  # By default, the pull_request event type is not triggered when a PR is merged into main
  push:
    branches:
      - main
      - develop
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Build Playwright environment
        run: docker build --tag playwright-test --file Dockerfile.playwright .

      - name: Run playwright tests
        run: docker run --env CI=true --volume $PWD/playwright-report:/app/playwright-report playwright-test

      - name: Upload test report
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
